---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
      version: 2.0.6
  interval: 1m0s
  values:
    adminUser:
      create: true
      passwordHash: $2a$10$B0WvpzlymVYonwPF/8bIguthzaUHv/8Xm4BPc5ht/pVP/FFKEgNaS
      username: admin
    ingress:
      enabled: true
      className: traefik
      annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
      hosts:
        - host: ww-gitops.fluxcd.172.18.0.2.nip.io
          paths:
            - path: /
              pathType: ImplementationSpecific

