---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo-frontend
spec:
  rules:
    - host: REPLACE_ME_INGRESS_PREFIX.REPLACE_ME_BASE_URL
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
