---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  cpe.decathlon.com/kustomize-component: podinfo/cache

resources:
  - resources/service.yaml
  - resources/deployment.yaml

configMapGenerator:
  - name: redis-config
    files:
      - configmap-data/redis-config/redis.conf
