---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-flux-guestbook-dir-fluxcd
  namespace: guestbook-dir-fluxcd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-flux-guestbook-dir-fluxcd
  namespace: guestbook-dir-fluxcd
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-flux-guestbook-dir-fluxcd
  namespace: guestbook-dir-fluxcd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-flux-guestbook-dir-fluxcd
subjects:
- kind: ServiceAccount
  name: sa-flux-guestbook-dir-fluxcd
  namespace: guestbook-dir-fluxcd
