---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-flux-podinfo-backend-kz-fluxcd
  namespace: podinfo-backend-kz-fluxcd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-flux-podinfo-backend-kz-fluxcd
  namespace: podinfo-backend-kz-fluxcd
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-flux-podinfo-backend-kz-fluxcd
  namespace: podinfo-backend-kz-fluxcd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-flux-podinfo-backend-kz-fluxcd
subjects:
  - kind: ServiceAccount
    name: sa-flux-podinfo-backend-kz-fluxcd
    namespace: podinfo-backend-kz-fluxcd
