---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  cpe.decathlon.com/kustomize-component: podinfo/frontend

resources:
  - resources/service.yaml
  - resources/deployment.yaml
  - resources/hpa.yaml
  - resources/ingress--frontend.yml
