---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-sops-demo-dir-fluxcd
  namespace: sops-demo-dir-fluxcd
spec:
  interval: 5m
  serviceAccountName: sa-flux-sops-demo-dir-fluxcd
  targetNamespace: sops-demo-dir-fluxcd
  path: "k8s/apps/fluxcd/directory/sops-demo"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
