apiVersion: v1
data:
    firstname: ENC[AES256_GCM,data:DE+tGy4/RSU=,iv:zUyjQJcnefhekLz+YVr2d8XrA8JazExow7ZgLbyNRw8=,tag:B4McUrtnlhCzyo1AHZ6IWQ==,type:str]
    hero: ENC[AES256_GCM,data:W3boVKvjkq/SThY5,iv:T0FWZ2wrM/Sl/9MXMBTHpnu3iSgs3q9MDJXg28ZrUQA=,tag:Hu4Nf2AGwlKjW8vMhyYBxA==,type:str]
    lastname: ENC[AES256_GCM,data:ovTVxmfh6ly+ggj2,iv:CsP8+AYBduLusk7H4zIDEB5FuM6YNjnsPhzGMWEQj2I=,tag:ntvQbvIgMd114OaENCrUfg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: identities
    namespace: sops-fluxcd
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-01T14:34:11Z"
    mac: ENC[AES256_GCM,data:viVfGInpyegFJpHbMxrmou0M2Xu3SwLNG3v6yBBbpMJFhVO+L13+xPjqOA0uS0rKySc2zM/Dz1uE6nvdq5aHaWQY4EhqZOxmDJNkRyyIUzZslA7KroY0VvmzgYM5jNlmtS/aRWXU4Xb2ROQyFkw2/hBLnTEZcL/DyCefOuruEHk=,iv:fPGWSalPlKYs6srR3C6qUyXf40hljjp9LeV/opqp+Dc=,tag:+bPTmulNQgmSx1cbBsLD0w==,type:str]
    pgp:
        - created_at: "2022-06-01T14:34:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7pFmCzQTkMDAQ/6Aou5eWQoUX5IZRb0i6b5IgvXuFw6QD9CJera+W0ZCqtZ
            VDWAvO6eVLtLAg4JBl0Yt7Bc/SfwI1wiXX32rwAAq69USZ5NLPjLqC/WZmToqzjk
            6Avkdxe/Yr8xJYCfkRGioq2h8bx//sXL0rtB5v+VH88hZB5lDQq7epkvCKyBFcQ3
            /7BCiVz+rhY6T1TXZPcaPJRXFzqOnrstNX8PQQW5j/I2sLgtj/eZvo7kG0Utf7Fr
            iPKb0sd6/MW8Sy5QNrt53fyrGGHjIMxhJyBHzCVmfviDNCnmtYoTyg6Y9wi6CaWP
            6pmPeffa6gf2edxaM+gd57vbI2PPo5a+wxNtFdf39oJ8yzt4I1kMAg+JYw4Momqg
            14YwZTOyHvxz5J5AAHZn0Q8NU6nCJ+vp33hvy8AqqUTUcz3gY8yn9fMkFZh/moLu
            4zp25mnHSoqIRunJbsdq7D7X+KB/WiE34zURxxrL0U7NaXkFKRPPU/45OVRbLYnM
            bSpuWSYCjXuzA4aMIP+48ZMZP5bcvXzRodjRUKrHJqxs5ai0M/4AdHCJiGmTadkY
            0GA/vb/ZKuxM91IWTz0UhPLNWm0JutAZKvjRQun66ruh69uiWDJbfXdYGxLbye2g
            8IpEaBYpmVdoROhDHgFWpW2UFRt4MNs7F4uYBWOtksmTvcojtEkrL64xCC6vl9LS
            XgHy7DSeEZLP1/cl+B6mBXklaLod8cK8fidrEHzCS5kMoUUzy9++JMt4g7zbp80I
            0O6MNKxksvyA0w7jE7AOkubstkwx8sgUY2ibMvd54jZUFT2uH6FUrFsvGy8Ubl0=
            =U3tj
            -----END PGP MESSAGE-----
          fp: 0CA153A64B2EF741193676C7976FDC1C0E24BCBE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
