---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-guestbook-dir-fluxcd
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/infra/fluxcd/k3d/namespaces/guestbook-dir-fluxcd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-guestbook-kz-fluxcd
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/infra/fluxcd/k3d/namespaces/guestbook-kz-fluxcd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-podinfo-backend-kz-fluxcd
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/infra/fluxcd/k3d/namespaces/podinfo-backend-kz-fluxcd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-podinfo-frontend-kz-fluxcd
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/infra/fluxcd/k3d/namespaces/podinfo-frontend-kz-fluxcd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-sops-demo-dir-fluxcd
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/infra/fluxcd/k3d/namespaces/sops-demo-dir-fluxcd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
