---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-ww-gitops
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/infra/fluxcd/k3d/weave-gitops
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
