---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-infra
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/infra/fluxcd/k3d/flux-infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
